
version: "3.9"

services:
  
  test_site:
    #image php:8.2.5RC1-apache-bullseye 
    build:
      context: .
      dockerfile: ./Dockerfile
    #command: chown -R www-data:www-data /var/www/html/photos 
    container_name: test_site
    ports:
      - "8080:80"
    volumes:
      - ./site:/var/www/html
    links:
      - db
    networks:
      - code_test

  db:
    image: mysql
    container_name: db
    volumes:
      - ./data:/var/lib/mysql
    environment:
      #- MYSQL_ROOT_PASSWORD:
      - MYSQL_ALLOW_EMPTY_PASSWORD='yes'
      - MYSQL_DATABASE=code_test_db
    restart: always
    ports:
      - "6033:3306"
    networks:
      - code_test

  pma:
    depends_on:
      - db
    image: phpmyadmin:5.2.0-apache
    container_name: pma
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - "80:8000"
    networks:
      - code_test

networks:
  code_test:
volumes: 
  data: 
